spring.application.name=jwt-security
server.port=8081
# Common JPA
spring.jpa.properties.hibernate.format_sql=true
# MVC
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
# REDIS
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.database=${REDIS_DATABASE}

spring.profiles.active=dev

eureka.client.service-url.defaultZone=http://localhost:8781/eureka/
eureka.instance.prefer-ip-address=true